### ISSUE TITLE
ByteBuddyBinder creates a new class on every method invocation

### ISSUE THREAD

**Issue by rocketraman** [jdiazcano/cfg4k#41] opened 2018-01-19 19:55 UTC
When using the ByteBuddy binder, every method invocation to a config object causes a new class to be created and loaded into memory. Instead, the binder should create the class only once, with the methods in the class reading the provider every time they are executed.

This is easy to reproduce. Create any config binding with ByteBuddy. Read a method on the config in a tight loop. Start the JVM with `-verbose:class` to see the problem.

**Comment by jdiazcano** [comment] 2018-01-19 21:57
As a work around while I fix this the Proxy binder can be used to avoid this.

**Comment by jdiazcano** [comment] 2018-01-20 11:53
I have been investigating this and "it is (more or less) working as intended". Here are the points:

* Since the class implements an interface, right now I'm using the DEFAULT_CONSTRUCTOR strategy to simply instantiate it (this is a key point for the possible rework)
* This only happens when you call bind, not all new objects (for example you won't have problems using it with a get string)
* There is the possibility of caching the provider so it will cache the object for the subsequent calls and cleared on reload. This cache was done in a different layer to not pollute all the providers with the same piece of code so by adding `.cache()` to the provider creation will cache it and won't create one class for every binder but there is the problem of creating one class for everytime it is reloaded (which I must think about).

Now about the fix of avoiding creating one class everytime it is reloaded (and even when you call bind many times without the cache):
* I need to investigate how it works to create a class with a constructor and create an instance with the properties map instead of creating and compiling a new class using the wrapper class values (I already tried at the start and failed thoguh)
* Even if I do this, if no cache is used, it will create a new object everytime `bind()` is called

**Comment by jdiazcano** [comment] 2018-01-20 18:49
So! I have been working on this since the message and I have reworked a little bit the file `ByteBuddyConfigProvider.kt` with the next changes:

* Now the created class is done only once per `type` (this means, only once per Class -interface in this case-) and cached.
* Now the generated classes have three fields:
    * Configprovider
    * Prefix
    * Type
* When cached only a new instance will be returned with the parameters passed
* Simplified the class generation and now the logic behind the configuration is in a separate class

So now there won't be N generated classes for the same interface and it should be even faster!

**Comment by jdiazcano** [comment] 2018-01-20 18:57
I just merged it to master!

**Closed as completed by jdiazcano** 2018-01-20 18:57 UTC
Labels: bug

**Comment by rocketraman** [comment] 2018-01-20 22:16
Awesome! Before I try the new code, here is a reliable reproduction recipe for this issue -- I believe the problem was manifesting in my code because of the `List<T>` in the config. You can see that the system defines the class `ItemConfig` twice for each loop iteration, once for each entry in the list:

Here is `test.conf`

```
items: {
  instances: [
    {
      "name": "foo"
    },
    {
      "name": "bar"
    }
  ]
}
```

And the program:

```
interface ItemsConfig {
  fun instances(): List<ItemConfig>
}

interface ItemConfig {
  fun name(): String
}

fun main(args: Array<String>) {
  val c = ByteBuddyConfigProvider(HoconConfigLoader("test.conf"))
  val d = c.bind<ItemsConfig>("items")
  while (true) {
    val l = d.instances()
    l.forEach { println(it.name()) }
    Thread.sleep(50)
  }
}
```

run with `-verbose:class` produces the output:

```
...
[Loaded TestCfg4k.ItemConfig$ByteBuddy$LlRKcVgj from __JVM_DefineClass__]
[Loaded TestCfg4k.ItemConfig$ByteBuddy$OrSH2pwv from __JVM_DefineClass__]
foo
bar
[Loaded TestCfg4k.ItemConfig$ByteBuddy$TCMMVYSm from __JVM_DefineClass__]
[Loaded TestCfg4k.ItemConfig$ByteBuddy$YAdkPijo from __JVM_DefineClass__]
foo
bar
[Loaded TestCfg4k.ItemConfig$ByteBuddy$803xr42O from __JVM_DefineClass__]
[Loaded TestCfg4k.ItemConfig$ByteBuddy$AWhmtMMI from __JVM_DefineClass__]
foo
bar
[Loaded TestCfg4k.ItemConfig$ByteBuddy$ZZcHYlzs from __JVM_DefineClass__]
[Loaded TestCfg4k.ItemConfig$ByteBuddy$lCe4RT6J from __JVM_DefineClass__]
foo
bar
...
```

**Comment by rocketraman** [comment] 2018-01-20 22:25
... and indeed I can confirm that your latest changes fix the issue and that `ItemConfig` in the repro recipe above is defined only once! Nice.
